version: '3.9'

services:
  api:
    build: ./api
    container_name: api
    ports:
      - "4000:4000"
    restart: always
    env_file: .env
    environment:
      - NODE_ENV=production

  bot:
    build: ./discord
    container_name: bot
    restart: always
    env_file: .env
    environment:
      - NODE_ENV=production
